version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: macl_vms
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - macl_network

  backend:
    build: ./backend
    restart: always
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      DB_HOST: mysql
      DB_DATABASE: macl_vms
      DB_USERNAME: user
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    networks:
      - macl_network

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - macl_network

volumes:
  mysql_data:

networks:
  macl_network:
    driver: bridge
